### ISSUE TITLE
1.21.3 crash when random ticking vault blocks

### ISSUE THREAD

**Issue by EmilieSong** [GammaTick/Reusable-Vault-Blocks#2]
[crash-2024-11-28_01.45.02-server.txt](https://github.com/user-attachments/files/17941793/crash-2024-11-28_01.45.02-server.txt)

**Comment by GammaTick** [comment]
The new version with the fix is now available for download. Huge thanks for the bug report! May you have a wonderful remainder of the day and may God bless you!
